language: node_js
node_js:
  - node

script:
  - yarn run build
  - yarn test

deploy:
  provider: s3
  access_key_id: ${ACCESS_KEY_ID}
  secret_access_key: ${SECRET_ACCESS_KEY}
  bucket: ${BUCKET_NAME}